import{a as q,S as M,i as c}from"./assets/vendor-BK_rxH-O.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const P="https://pixabay.com/api/",B="23963114-6d0d5d874ae460d9125bacd21";async function f(r,t=1){const s={key:B,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};return(await q.get(P,{params:s})).data}let $=new M(".gallery a",{captionsData:"alt",captionDelay:250});function g(r){const t=document.querySelector(".gallery"),s=r.map(({webformatURL:a,largeImageURL:e,tags:o,likes:n,views:L,comments:w,downloads:S})=>`
        <li class="gallery-item">
          <a href="${e}" class="gallery-link">
            <img src="${a}" alt="${o}" class="gallery-image" />
          </a>
          <div class="image-info">
            <div class="image-info-item"><span><b>Likes</b></span><span>${n}</span></div>
            <div class="image-info-item"><span><b>Views</b></span><span>${L}</span></div>
            <div class="image-info-item"><span><b>Comments</b></span><span>${w}</span></div>
            <div class="image-info-item"><span><b>Downloads</b></span><span>${S}</span></div>
          </div>
        </li>
      `).join("");t.insertAdjacentHTML("beforeend",s),$.refresh()}function R(){document.querySelector(".gallery").innerHTML=""}const h=document.querySelector(".load-more"),y=document.querySelector(".loader-wrapper");function v(){y.classList.remove("is-hidden")}function d(){y.classList.add("is-hidden")}function E(){h.classList.remove("is-hidden")}function u(){h.classList.add("is-hidden")}const m=document.querySelector(".form"),O=document.querySelector(".load-more");let l="",i=1;const b=15;let p=0;m.addEventListener("submit",async function(r){if(r.preventDefault(),l=m.elements["search-text"].value.trim(),!!l){i=1,R(),u(),v();try{const{hits:t,totalHits:s}=await f(l,i);if(d(),t.length===0){c.warning({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}p=s,g(t),E();const a=Math.ceil(p/b);i>=a&&(u(),c.info({message:"The end of search results.",position:"topRight"}))}catch{d(),c.error({message:"We are sorry, but you have reached the end of search results.",position:"topRight"})}}});O.addEventListener("click",async()=>{i+=1,v();try{const{hits:r}=await f(l,i);g(r);const t=Math.ceil(p/b);i>=t&&(u(),c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),d();const{height:s}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})}catch{d(),c.error({message:"Error",position:"topRight"})}});
//# sourceMappingURL=index.js.map
